version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432