name: build master branch
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Checkout code and test, clean build
    runs-on: ubuntu-latest
    steps:
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '16'
      - name: Checkout code
        uses: actions/checkout@master
      - name: Build with Maven
        run: mvn -B package --file pom.xml